/**
 * Conversation turns (#93, #122, #200, #241, #283): a `send`, or a `type` into a message-shaped
 * field — generated by `chatReply` from the latest reply, capped, never a repeat of an earlier message,
 * and a sent message's reply awaited. The goal loop's message handler, moved out of `explore.ts`
 * unchanged (#232). `op` / `forcedNote` come from the loop's repeated-type check.
 */

import { act } from "../act.js";
import {
  STUCK_TURNS,
  lastQuestion,
  newPageText,
  readPageText,
  repetitiveTurns,
  sameMessage,
  waitForReply,
  type ReplyResult,
} from "../conversation.js";
import type { Decision } from "../decide.js";
import { chatReply } from "../fill.js";
import { monitorFor } from "../page-monitor.js";
import { backgroundEndpoints, requestsStartedSince, writesStartedSince } from "../stuck-actions.js";
import type { RunContext } from "./context.js";
import { firstLine, keyOf, noReply, quote } from "./helpers.js";
import { MAX_REPEAT_TYPE_SIGNALS } from "./limits.js";
import type { ActStep, Flow } from "./step.js";

export async function handleMessage(ctx: RunContext, step: ActStep, op: Decision["op"], forcedNote: string | null): Promise<Flow> {
  const { cfg } = ctx;
  const { snap, keys, record, control, at } = step;
  // Stuck detection (independent code, #122): the last user turns only acknowledged / promised,
  // or said the same thing again. The next turn is generated with the stuck brief (answer the
  // assistant's question with a concrete fact or choice), the decision is pointed at the
  // page's call to action, and a conversation still stuck after that ends the run.
  const stuck = repetitiveTurns(ctx.conversation.sent);
  ctx.stuckTurns = stuck ? ctx.stuckTurns + 1 : 0;
  if (ctx.stuckTurns > STUCK_TURNS) {
    const reason = `stuck: the messages kept acknowledging or repeating without answering the assistant (still after ${STUCK_TURNS} nudged turns)`;
    record(false, reason, { op });
    ctx.incomplete = reason;
    ctx.stop = "no-progress";
    return "stop";
  }
  let text: string | null;
  try {
    text = await chatReply(cfg.gen, {
      goal: cfg.goal,
      fieldLabel: control.name || control.summary,
      latestReply: ctx.conversation.latestReply,
      sentMessages: ctx.conversation.sent,
      maxChars: ctx.replyMaxChars,
      secrets: ctx.secrets,
      question: lastQuestion(ctx.conversation.latestReply),
      stuck,
    });
  } catch (e) {
    const reason = `message generation unavailable: ${firstLine(e)}`;
    ctx.history.push(`${op} skipped: ${reason}`);
    record(false, reason, { op, origin: "engine" });
    ctx.lastActedOp = op;
    return "continue";
  }
  if (text === null) {
    ctx.blockers.failClosed = `no message for ${quote(control.name || control.summary, 80)} (the message generator returned none)`;
    record(false, "no message available (fail-closed)", { op, origin: "engine" });
    ctx.incomplete = "no message could be generated for the conversation";
    ctx.stop = "blocked";
    return "stop";
  }
  const message = text;
  if (ctx.conversation.sent.some((m) => sameMessage(m, message))) {
    const n = ctx.unsent.noteRepeat();
    const reason = `message not sent: it repeats an earlier message (stuck signal ${n}/${MAX_REPEAT_TYPE_SIGNALS})`;
    ctx.history.push(`${reason} — answer the latest reply with something new`);
    record(false, reason, { op, message, origin: "engine" });
    ctx.lastActedOp = op;
    if (n >= MAX_REPEAT_TYPE_SIGNALS) {
      ctx.incomplete = "stuck: the generated messages kept repeating";
      ctx.stop = "no-progress";
      return "stop";
    }
    return "continue";
  }
  if (op === "send") {
    const baseline = await readPageText(ctx.page, ctx.secrets);
    const before = new Set(keys.keys());
    const sendBackground = backgroundEndpoints(monitorFor(ctx.page), at, ctx.turnWrites);
    const r = await act(cfg.actor, { op: "send", control, value: message, candidates: snap.controls });
    if (!r.ok) {
      ctx.history.push(`send failed: ${r.reason ?? "?"}`);
      record(false, forcedNote === null ? r.reason : `${forcedNote}; ${r.reason ?? ""}`, { op, message });
      ctx.lastActedOp = op;
      if (await ctx.noteFailedAct(control, r.reason)) return "stop";
      return "continue";
    }
    // #241: a send that started no request and changed nothing on the page was not sent (Enter
    // in a field whose real submit is a separate control): a failed send, never a pending reply.
    const checkedFrom = ctx.now();
    await monitorFor(ctx.page).waitSettled({ ceilingMs: 3_000 }).catch(() => undefined);
    if (
      requestsStartedSince(monitorFor(ctx.page), at, sendBackground).length === 0 &&
      newPageText(baseline, await readPageText(ctx.page, ctx.secrets), "").trim() === ""
    ) {
      const reason = `message was not sent: ${r.submittedVia?.kind === "click" ? `clicking ${quote(r.submittedVia.control.name, 40)}` : "Enter"} in ${quote(control.name || control.summary, 60)} started no request and changed nothing on the page`;
      ctx.history.push(`${reason} — look for a send / continue control that submits it (it may need something else first)`);
      record(false, reason, { op, message });
      ctx.lastActedOp = op;
      if (await ctx.noteFailedAct(control, reason)) return "stop";
      return "continue";
    }
    ctx.recorder.fill(control.descriptor, message, at);
    const via = r.submittedVia;
    if (via !== undefined && via.kind === "click") ctx.recorder.click(via.control.descriptor, ctx.now());
    else ctx.recorder.press("Enter", control.descriptor, ctx.now());
    ctx.noteMutation(`send ${control.name}`, control.descriptor, snap.signature, at, { field: keyOf(control), value: message });
    ctx.tracker.countAction();
    ctx.unsent.submitted();
    ctx.conversation.sent.push(message);
    ctx.preSend ??= baseline;
    // The reply wait counts from the send: the check above already waited part of it.
    const checkedMs = ctx.now() - checkedFrom;
    // The send's own writes (started by now: the not-sent check above settled) — never background.
    for (const k of writesStartedSince(monitorFor(ctx.page), at, ctx.isWrite)) if (!sendBackground.has(k)) ctx.turnWrites.add(k);
    const listened = await waitForReply(ctx.page, {
      secrets: ctx.secrets,
      baseline,
      sent: message,
      sentAt: at,
      background: sendBackground,
      timeoutMs: Math.max(1, ctx.replyWaitMs - checkedMs),
      ceilingMs: Math.max(1, ctx.replyCeilingMs - checkedMs),
      quietMs: ctx.replyQuietMs,
    });
    const reply: ReplyResult = { ...listened, waitedMs: listened.waitedMs + checkedMs };
    // #390: the reply is told below — the progress check does not tell its text again.
    ctx.replyTold = reply.received;
    if (reply.received) {
      ctx.conversation.latestReply = reply.text;
      ctx.replies.add(snap.url, reply.text);
    }
    ctx.awaitingReply = !reply.received;
    ctx.busyWaitedMs = 0;
    ctx.replyWaitedMs = reply.waitedMs;
    ctx.lastTurn = { baseline, sent: message, sentAt: at, background: sendBackground };
    ctx.offerBaseline = before;
    ctx.history.push(
      `sent ${quote(message)} via ${via?.kind === "click" ? `"${via.control.name}"` : "Enter"} → ` +
        (reply.received ? `reply: ${quote(reply.text, 300)}` : noReply(reply)),
    );
    ctx.noteStuckConversation(snap.controls);
    record(true, forcedNote ?? undefined, { op, message, reply });
    ctx.lastActedOp = op;
    return "continue";
  }
  // A plain `type` of a message: typed, NOT sent yet (the Send control or Enter still has to follow).
  const r = await act(cfg.actor, { op: "type", control, value: message });
  if (r.ok) {
    ctx.recorder.fill(control.descriptor, message, at);
    ctx.noteMutation(`type ${control.name}`, control.descriptor, snap.signature, at, { field: keyOf(control), value: message });
    ctx.tracker.countAction();
    ctx.unsent.typed(keyOf(control), control.name, message, true);
    ctx.history.push(`typed ${quote(message, 80)} into ${control.name} — NOT sent yet (send it)`);
  } else {
    ctx.history.push(`type failed: ${r.reason ?? "?"}`);
  }
  record(r.ok, r.reason, { message });
  ctx.lastActedOp = op;
  if (!r.ok && (await ctx.noteFailedAct(control, r.reason))) return "stop";
  return "continue";
}
